CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE branches (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Code" text NOT NULL,
    "Address" text,
    "Phone" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_branches" PRIMARY KEY ("Id")
);

CREATE TABLE nexora_services (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_nexora_services" PRIMARY KEY ("Id")
);

CREATE TABLE payments (
    "Id" uuid NOT NULL,
    "RecordType" text NOT NULL,
    "RecordId" uuid NOT NULL,
    "PaymentDate" date,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalAmount" numeric NOT NULL,
    "PaidAmount" numeric NOT NULL,
    "RemainingAmount" numeric NOT NULL,
    "PaymentOption" integer,
    "PaymentStatus" integer,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_payments" PRIMARY KEY ("Id")
);

CREATE TABLE sync_tracking (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TableName" text NOT NULL,
    "RecordId" uuid NOT NULL,
    "Operation" integer NOT NULL,
    "SyncedAt" timestamp with time zone,
    "DeviceId" text,
    "ConflictResolved" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_sync_tracking" PRIMARY KEY ("Id")
);

CREATE TABLE clients (
    "Id" uuid NOT NULL,
    "ClientCode" text NOT NULL,
    "ClientName" text NOT NULL,
    "Email" text,
    "Phone" text,
    "Status" integer NOT NULL,
    "BranchId" uuid,
    "TotalRevenue" numeric NOT NULL,
    "OutstandingBalance" numeric NOT NULL,
    "LogoStorageKey" text,
    "LastActiveAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_clients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_clients_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id")
);

CREATE TABLE users (
    "Id" uuid NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text,
    "UserLogo" text,
    "PasswordHash" text NOT NULL,
    "Role" integer NOT NULL,
    "BranchId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "LastLoginAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_users_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id") ON DELETE CASCADE
);

CREATE TABLE cheque_details (
    "Id" uuid NOT NULL,
    "PaymentId" uuid NOT NULL,
    "BankName" text,
    "ChequeNumber" text,
    "ChequeDate" date,
    "Status" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_cheque_details" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_cheque_details_payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES payments ("Id") ON DELETE CASCADE
);

CREATE TABLE boi_registrations (
    "Id" uuid NOT NULL,
    "BoiCode" text,
    "Assignment" text,
    "Country" text,
    "CountryAddress" text,
    "InvestmentValueUsd" numeric,
    "Status" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "PaymentStatus" text,
    "BranchId" uuid,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_boi_registrations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_boi_registrations_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_boi_registrations_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE business_plan_valuations (
    "Id" uuid NOT NULL,
    "Assignment" text,
    "Status" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "PaymentStatus" text,
    "BranchId" uuid,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_business_plan_valuations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_business_plan_valuations_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_business_plan_valuations_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE company_registrations (
    "Id" uuid NOT NULL,
    "RegistrationCode" text NOT NULL,
    "RegistrationDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text NOT NULL,
    "CompanyType" text,
    "Objective" text,
    "Address" text,
    "Email" text,
    "Phone" text,
    "PaymentStatus" text,
    "Process" text,
    "Description" text,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "BranchId" uuid,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_company_registrations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_company_registrations_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_company_registrations_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE epf_etf_records (
    "Id" uuid NOT NULL,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text NOT NULL,
    "NumberOfStaff" integer NOT NULL,
    "Process" text,
    "Phone" text,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "PaymentStatus" text,
    "BranchId" uuid,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_epf_etf_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_epf_etf_records_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_epf_etf_records_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE hr_management_consulting (
    "Id" uuid NOT NULL,
    "Assignment" text,
    "Status" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "PaymentStatus" text,
    "BranchId" uuid,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_hr_management_consulting" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_hr_management_consulting_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_hr_management_consulting_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE import_export_clearances (
    "Id" uuid NOT NULL,
    "ClearanceCode" text,
    "Assignment" text,
    "TinNumber" text,
    "Status" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "PaymentStatus" text,
    "BranchId" uuid,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_import_export_clearances" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_import_export_clearances_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_import_export_clearances_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE nexora_service_requests (
    "Id" uuid NOT NULL,
    "RequestDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text,
    "ServiceId" uuid,
    "Phone" text,
    "Notes" text,
    "BranchId" uuid,
    "Status" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_nexora_service_requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_nexora_service_requests_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_nexora_service_requests_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id"),
    CONSTRAINT "FK_nexora_service_requests_nexora_services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES nexora_services ("Id")
);

CREATE TABLE other_secretarial_records (
    "Id" uuid NOT NULL,
    "Assignment" text,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "PaymentStatus" text,
    "BranchId" uuid,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_other_secretarial_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_other_secretarial_records_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_other_secretarial_records_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE tax_filings (
    "Id" uuid NOT NULL,
    "FilingCode" text NOT NULL,
    "TaxType" text NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "BranchId" uuid,
    "FilingDate" date NOT NULL,
    "TaxNumber" text NOT NULL,
    "PeriodNumber" text,
    "PeriodType" text,
    "PaymentStatus" text,
    "Notes" text,
    "IsDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_tax_filings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tax_filings_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_tax_filings_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE trade_licenses (
    "Id" uuid NOT NULL,
    "LicenseCode" text,
    "Assignment" text,
    "Status" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "PaymentStatus" text,
    "BranchId" uuid,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_trade_licenses" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_trade_licenses_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_trade_licenses_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE trade_marks (
    "Id" uuid NOT NULL,
    "TrademarkCode" text,
    "Status" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "CompanyName" text,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "PaymentStatus" text,
    "BranchId" uuid,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_trade_marks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_trade_marks_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_trade_marks_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id")
);

CREATE TABLE activity_logs (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp with time zone NOT NULL,
    "UserId" uuid,
    "BranchId" uuid,
    "Action" text NOT NULL,
    "Module" text NOT NULL,
    "RecordType" text,
    "RecordId" uuid,
    "Description" text,
    "IpAddress" text,
    "UserAgent" text,
    CONSTRAINT "PK_activity_logs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_activity_logs_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_activity_logs_users_UserId" FOREIGN KEY ("UserId") REFERENCES users ("Id")
);

CREATE TABLE audit_assurance_records (
    "Id" uuid NOT NULL,
    "Assignment" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "BranchId" uuid,
    "ClientLogo" text,
    "PaymentStatus" text,
    "Process" text NOT NULL,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "Notes" text,
    "IsDeleted" boolean NOT NULL,
    "CreatorId" uuid,
    CONSTRAINT "PK_audit_assurance_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_audit_assurance_records_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_audit_assurance_records_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id"),
    CONSTRAINT "FK_audit_assurance_records_users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES users ("Id")
);

CREATE TABLE documents (
    "Id" uuid NOT NULL,
    "RecordType" text NOT NULL,
    "RecordId" uuid NOT NULL,
    "DocumentCategory" text,
    "FileName" text NOT NULL,
    "FileSize" text,
    "MimeType" text,
    "StorageKey" text NOT NULL,
    "Description" text,
    "UploadedBy" uuid,
    "UploadedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "UploaderId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_documents_users_UploaderId" FOREIGN KEY ("UploaderId") REFERENCES users ("Id")
);

CREATE TABLE forensic_audit_records (
    "Id" uuid NOT NULL,
    "Assignment" text,
    "PeriodNumber" text,
    "PeriodType" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "BranchId" uuid,
    "ClientLogo" text,
    "PaymentStatus" text,
    "Process" text NOT NULL,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "Notes" text,
    "IsDeleted" boolean NOT NULL,
    "CreatorId" uuid,
    CONSTRAINT "PK_forensic_audit_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_forensic_audit_records_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_forensic_audit_records_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id"),
    CONSTRAINT "FK_forensic_audit_records_users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES users ("Id")
);

CREATE TABLE internal_audit_records (
    "Id" uuid NOT NULL,
    "Assignment" text,
    "PeriodNumber" text,
    "PeriodType" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "BranchId" uuid,
    "ClientLogo" text,
    "PaymentStatus" text,
    "Process" text NOT NULL,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "Notes" text,
    "IsDeleted" boolean NOT NULL,
    "CreatorId" uuid,
    CONSTRAINT "PK_internal_audit_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_internal_audit_records_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_internal_audit_records_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id"),
    CONSTRAINT "FK_internal_audit_records_users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES users ("Id")
);

CREATE TABLE internal_control_records (
    "Id" uuid NOT NULL,
    "Assignment" text,
    "PeriodNumber" text,
    "PeriodType" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "BranchId" uuid,
    "ClientLogo" text,
    "PaymentStatus" text,
    "Process" text NOT NULL,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "Notes" text,
    "IsDeleted" boolean NOT NULL,
    "CreatorId" uuid,
    CONSTRAINT "PK_internal_control_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_internal_control_records_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_internal_control_records_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id"),
    CONSTRAINT "FK_internal_control_records_users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES users ("Id")
);

CREATE TABLE management_account_records (
    "Id" uuid NOT NULL,
    "Assignment" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "BranchId" uuid,
    "ClientLogo" text,
    "PaymentStatus" text,
    "Process" text NOT NULL,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "Notes" text,
    "IsDeleted" boolean NOT NULL,
    "CreatorId" uuid,
    CONSTRAINT "PK_management_account_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_management_account_records_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_management_account_records_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id"),
    CONSTRAINT "FK_management_account_records_users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES users ("Id")
);

CREATE TABLE other_audit_records (
    "Id" uuid NOT NULL,
    "Assignment" text,
    "Description" text,
    "Company" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "BranchId" uuid,
    "ClientLogo" text,
    "PaymentStatus" text,
    "Process" text NOT NULL,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "Notes" text,
    "IsDeleted" boolean NOT NULL,
    "CreatorId" uuid,
    CONSTRAINT "PK_other_audit_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_other_audit_records_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_other_audit_records_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id"),
    CONSTRAINT "FK_other_audit_records_users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES users ("Id")
);

CREATE TABLE tax_account_records (
    "Id" uuid NOT NULL,
    "AssignedTo" uuid,
    "AssignedUserId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    "RecordCode" text NOT NULL,
    "RecordDate" date NOT NULL,
    "ClientId" uuid,
    "ClientName" text NOT NULL,
    "BranchId" uuid,
    "ClientLogo" text,
    "PaymentStatus" text,
    "Process" text NOT NULL,
    "SubTotal" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "TotalPayment" numeric NOT NULL,
    "PartialAmount" numeric NOT NULL,
    "PaymentOption" text,
    "Notes" text,
    "IsDeleted" boolean NOT NULL,
    "CreatorId" uuid,
    CONSTRAINT "PK_tax_account_records" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tax_account_records_branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES branches ("Id"),
    CONSTRAINT "FK_tax_account_records_clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES clients ("Id"),
    CONSTRAINT "FK_tax_account_records_users_AssignedUserId" FOREIGN KEY ("AssignedUserId") REFERENCES users ("Id"),
    CONSTRAINT "FK_tax_account_records_users_CreatorId" FOREIGN KEY ("CreatorId") REFERENCES users ("Id")
);

CREATE TABLE company_officers (
    "Id" uuid NOT NULL,
    "CompanyRegistrationId" uuid NOT NULL,
    "Name" text NOT NULL,
    "Position" text,
    "OfficerType" text NOT NULL,
    "SharePercentage" numeric,
    "NicNumber" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_company_officers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_company_officers_company_registrations_CompanyRegistrationId" FOREIGN KEY ("CompanyRegistrationId") REFERENCES company_registrations ("Id") ON DELETE CASCADE
);

CREATE TABLE epf_etf_staff (
    "Id" uuid NOT NULL,
    "EpfEtfRecordId" uuid NOT NULL,
    "StaffCode" text NOT NULL,
    "StaffName" text NOT NULL,
    "Phone" text,
    "Process" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" uuid,
    CONSTRAINT "PK_epf_etf_staff" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_epf_etf_staff_epf_etf_records_EpfEtfRecordId" FOREIGN KEY ("EpfEtfRecordId") REFERENCES epf_etf_records ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_activity_logs_BranchId" ON activity_logs ("BranchId");

CREATE INDEX "IX_activity_logs_UserId" ON activity_logs ("UserId");

CREATE INDEX "IX_audit_assurance_records_BranchId" ON audit_assurance_records ("BranchId");

CREATE INDEX "IX_audit_assurance_records_ClientId" ON audit_assurance_records ("ClientId");

CREATE INDEX "IX_audit_assurance_records_CreatorId" ON audit_assurance_records ("CreatorId");

CREATE INDEX "IX_boi_registrations_BranchId" ON boi_registrations ("BranchId");

CREATE INDEX "IX_boi_registrations_ClientId" ON boi_registrations ("ClientId");

CREATE INDEX "IX_business_plan_valuations_BranchId" ON business_plan_valuations ("BranchId");

CREATE INDEX "IX_business_plan_valuations_ClientId" ON business_plan_valuations ("ClientId");

CREATE INDEX "IX_cheque_details_PaymentId" ON cheque_details ("PaymentId");

CREATE INDEX "IX_clients_BranchId" ON clients ("BranchId");

CREATE INDEX "IX_company_officers_CompanyRegistrationId" ON company_officers ("CompanyRegistrationId");

CREATE INDEX "IX_company_registrations_BranchId" ON company_registrations ("BranchId");

CREATE INDEX "IX_company_registrations_ClientId" ON company_registrations ("ClientId");

CREATE INDEX "IX_documents_UploaderId" ON documents ("UploaderId");

CREATE INDEX "IX_epf_etf_records_BranchId" ON epf_etf_records ("BranchId");

CREATE INDEX "IX_epf_etf_records_ClientId" ON epf_etf_records ("ClientId");

CREATE INDEX "IX_epf_etf_staff_EpfEtfRecordId" ON epf_etf_staff ("EpfEtfRecordId");

CREATE INDEX "IX_forensic_audit_records_BranchId" ON forensic_audit_records ("BranchId");

CREATE INDEX "IX_forensic_audit_records_ClientId" ON forensic_audit_records ("ClientId");

CREATE INDEX "IX_forensic_audit_records_CreatorId" ON forensic_audit_records ("CreatorId");

CREATE INDEX "IX_hr_management_consulting_BranchId" ON hr_management_consulting ("BranchId");

CREATE INDEX "IX_hr_management_consulting_ClientId" ON hr_management_consulting ("ClientId");

CREATE INDEX "IX_import_export_clearances_BranchId" ON import_export_clearances ("BranchId");

CREATE INDEX "IX_import_export_clearances_ClientId" ON import_export_clearances ("ClientId");

CREATE INDEX "IX_internal_audit_records_BranchId" ON internal_audit_records ("BranchId");

CREATE INDEX "IX_internal_audit_records_ClientId" ON internal_audit_records ("ClientId");

CREATE INDEX "IX_internal_audit_records_CreatorId" ON internal_audit_records ("CreatorId");

CREATE INDEX "IX_internal_control_records_BranchId" ON internal_control_records ("BranchId");

CREATE INDEX "IX_internal_control_records_ClientId" ON internal_control_records ("ClientId");

CREATE INDEX "IX_internal_control_records_CreatorId" ON internal_control_records ("CreatorId");

CREATE INDEX "IX_management_account_records_BranchId" ON management_account_records ("BranchId");

CREATE INDEX "IX_management_account_records_ClientId" ON management_account_records ("ClientId");

CREATE INDEX "IX_management_account_records_CreatorId" ON management_account_records ("CreatorId");

CREATE INDEX "IX_nexora_service_requests_BranchId" ON nexora_service_requests ("BranchId");

CREATE INDEX "IX_nexora_service_requests_ClientId" ON nexora_service_requests ("ClientId");

CREATE INDEX "IX_nexora_service_requests_ServiceId" ON nexora_service_requests ("ServiceId");

CREATE INDEX "IX_other_audit_records_BranchId" ON other_audit_records ("BranchId");

CREATE INDEX "IX_other_audit_records_ClientId" ON other_audit_records ("ClientId");

CREATE INDEX "IX_other_audit_records_CreatorId" ON other_audit_records ("CreatorId");

CREATE INDEX "IX_other_secretarial_records_BranchId" ON other_secretarial_records ("BranchId");

CREATE INDEX "IX_other_secretarial_records_ClientId" ON other_secretarial_records ("ClientId");

CREATE INDEX "IX_tax_account_records_AssignedUserId" ON tax_account_records ("AssignedUserId");

CREATE INDEX "IX_tax_account_records_BranchId" ON tax_account_records ("BranchId");

CREATE INDEX "IX_tax_account_records_ClientId" ON tax_account_records ("ClientId");

CREATE INDEX "IX_tax_account_records_CreatorId" ON tax_account_records ("CreatorId");

CREATE INDEX "IX_tax_filings_BranchId" ON tax_filings ("BranchId");

CREATE INDEX "IX_tax_filings_ClientId" ON tax_filings ("ClientId");

CREATE INDEX "IX_trade_licenses_BranchId" ON trade_licenses ("BranchId");

CREATE INDEX "IX_trade_licenses_ClientId" ON trade_licenses ("ClientId");

CREATE INDEX "IX_trade_marks_BranchId" ON trade_marks ("BranchId");

CREATE INDEX "IX_trade_marks_ClientId" ON trade_marks ("ClientId");

CREATE INDEX "IX_users_BranchId" ON users ("BranchId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260325122011_InitialCreate', '9.0.2');

-- Client Code Auto-Generation
CREATE SEQUENCE IF NOT EXISTS client_code_seq START 1;

CREATE OR REPLACE FUNCTION generate_client_code()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW."ClientCode" IS NULL OR NEW."ClientCode" = '' THEN
        NEW."ClientCode" := 'CL-' || LPAD(nextval('client_code_seq')::TEXT, 5, '0');
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_generate_client_code
BEFORE INSERT ON clients
FOR EACH ROW
EXECUTE FUNCTION generate_client_code();

COMMIT;

